<?php

/* @TestRunner/travis.yml.twig */
class __TwigTemplate_ccdc62d34016838aa64b55d7fb2d9dea828492cd65cf3432001d06040ee2443a extends Twig_Template
{
    public function __construct(Twig_Environment $env)
    {
        parent::__construct($env);

        $this->parent = false;

        $this->blocks = array(
        );
    }

    protected function doDisplay(array $context, array $blocks = array())
    {
        // line 1
        echo "# do not edit this file manually, instead run the generate:travis-yml console command
";
        // line 2
        if (twig_test_empty((isset($context["pluginName"]) ? $context["pluginName"] : $this->getContext($context, "pluginName")))) {
            // line 3
            echo "# if you are a Piwik core developer, edit this template file to auto generate the .travis.yml: https://github.com/piwik/piwik/blob/master/plugins/TestRunner/templates/travis.yml.twig

# when modifying this file, please consider whether your changes should apply to plugin .travis.yml files. if not, check whether the pluginName twig var is empty,
# otherwise your changes will be synced with every plugin that uses an auto generated .travis.yml

# also please test generation before committing by running ./console generate:travis-yml --core and ./console generate:travis-yml --plugin=CustomAlerts
# and making sure the .travis.yml files are changed correctly
";
        }
        // line 11
        echo "
language: php

";
        // line 14
        if (twig_test_empty(((array_key_exists("phpVersions", $context)) ? (_twig_default_filter((isset($context["phpVersions"]) ? $context["phpVersions"] : $this->getContext($context, "phpVersions")))) : ("")))) {
            // line 15
            echo "php:
  - 5.6
  - 5.3.3
#  - hhvm
";
        } else {
            // line 20
            echo "php:
";
            // line 21
            $context['_parent'] = (array) $context;
            $context['_seq'] = twig_ensure_traversable((isset($context["phpVersions"]) ? $context["phpVersions"] : $this->getContext($context, "phpVersions")));
            foreach ($context['_seq'] as $context["_key"] => $context["version"]) {
                echo "  - ";
                echo $context["version"];
                echo "
";
            }
            $_parent = $context['_parent'];
            unset($context['_seq'], $context['_iterated'], $context['_key'], $context['version'], $context['_parent'], $context['loop']);
            $context = array_intersect_key($context, $_parent) + $_parent;
        }
        // line 24
        echo "
# Separate different test suites
";
        // line 26
        if (twig_test_empty(((array_key_exists("existingEnv", $context)) ? (_twig_default_filter((isset($context["existingEnv"]) ? $context["existingEnv"] : $this->getContext($context, "existingEnv")))) : ("")))) {
            // line 27
            echo "env:
  global:
    - PLUGIN_NAME=";
            // line 29
            echo (isset($context["pluginName"]) ? $context["pluginName"] : $this->getContext($context, "pluginName"));
            echo "
";
            // line 30
            if (twig_test_empty((isset($context["pluginName"]) ? $context["pluginName"] : $this->getContext($context, "pluginName")))) {
                // line 31
                echo "    - PIWIK_ROOT_DIR=\$TRAVIS_BUILD_DIR
";
            } else {
                // line 33
                echo "    - PIWIK_ROOT_DIR=\$TRAVIS_BUILD_DIR/piwik
";
            }
            // line 35
            if ((!twig_test_empty(((array_key_exists("extraGlobalEnvVars", $context)) ? (_twig_default_filter((isset($context["extraGlobalEnvVars"]) ? $context["extraGlobalEnvVars"] : $this->getContext($context, "extraGlobalEnvVars")))) : (""))))) {
                $context['_parent'] = (array) $context;
                $context['_seq'] = twig_ensure_traversable((isset($context["extraGlobalEnvVars"]) ? $context["extraGlobalEnvVars"] : $this->getContext($context, "extraGlobalEnvVars")));
                foreach ($context['_seq'] as $context["_key"] => $context["var"]) {
                    echo "    - ";
                    echo $context["var"];
                    echo "
";
                }
                $_parent = $context['_parent'];
                unset($context['_seq'], $context['_iterated'], $context['_key'], $context['var'], $context['_parent'], $context['loop']);
                $context = array_intersect_key($context, $_parent) + $_parent;
            }
            // line 37
            echo "  matrix:
";
            // line 38
            $context['_parent'] = (array) $context;
            $context['_seq'] = twig_ensure_traversable((isset($context["testsToRun"]) ? $context["testsToRun"] : $this->getContext($context, "testsToRun")));
            foreach ($context['_seq'] as $context["_key"] => $context["test"]) {
                echo "    - TEST_SUITE=";
                echo $this->getAttribute($context["test"], "name", array());
                echo " ";
                echo $this->getAttribute($context["test"], "vars", array());
                echo "
";
            }
            $_parent = $context['_parent'];
            unset($context['_seq'], $context['_iterated'], $context['_key'], $context['test'], $context['_parent'], $context['loop']);
            $context = array_intersect_key($context, $_parent) + $_parent;
        } else {
            // line 41
            echo "env:
  ";
            // line 42
            echo trim((isset($context["existingEnv"]) ? $context["existingEnv"] : $this->getContext($context, "existingEnv")));
            echo "
";
        }
        // line 44
        echo "
";
        // line 45
        if (twig_test_empty(((array_key_exists("existingMatrix", $context)) ? (_twig_default_filter((isset($context["existingMatrix"]) ? $context["existingMatrix"] : $this->getContext($context, "existingMatrix")))) : ("")))) {
            // line 46
            if ((!twig_test_empty((isset($context["testsToExclude"]) ? $context["testsToExclude"] : $this->getContext($context, "testsToExclude"))))) {
                // line 47
                echo "matrix:
  exclude:
";
                // line 49
                $context['_parent'] = (array) $context;
                $context['_seq'] = twig_ensure_traversable((isset($context["testsToExclude"]) ? $context["testsToExclude"] : $this->getContext($context, "testsToExclude")));
                foreach ($context['_seq'] as $context["_key"] => $context["testExclude"]) {
                    // line 50
                    if ((!twig_test_empty((($this->getAttribute($context["testExclude"], "description", array(), "any", true, true)) ? (_twig_default_filter($this->getAttribute($context["testExclude"], "description", array()))) : (""))))) {
                        echo "    # ";
                        echo $this->getAttribute($context["testExclude"], "description", array());
                        echo "
";
                    }
                    // line 52
                    echo "    - php: ";
                    echo $this->getAttribute($context["testExclude"], "php", array());
                    echo "
      env: ";
                    // line 53
                    echo $this->getAttribute($context["testExclude"], "env", array());
                    echo "
";
                }
                $_parent = $context['_parent'];
                unset($context['_seq'], $context['_iterated'], $context['_key'], $context['testExclude'], $context['_parent'], $context['loop']);
                $context = array_intersect_key($context, $_parent) + $_parent;
            }
        } else {
            // line 57
            echo "matrix:
  ";
            // line 58
            echo trim((isset($context["existingMatrix"]) ? $context["existingMatrix"] : $this->getContext($context, "existingMatrix")));
            echo "
";
        }
        // line 60
        echo "
script: \$PIWIK_ROOT_DIR/tests/travis/travis.sh

before_install:
";
        // line 64
        if ((!twig_test_empty((($this->getAttribute($this->getAttribute((isset($context["customTravisBuildSteps"]) ? $context["customTravisBuildSteps"] : null), "before_install", array(), "any", false, true), "before", array(), "any", true, true)) ? (_twig_default_filter($this->getAttribute($this->getAttribute((isset($context["customTravisBuildSteps"]) ? $context["customTravisBuildSteps"] : null), "before_install", array(), "any", false, true), "before", array()))) : (""))))) {
            echo $this->getAttribute($this->getAttribute((isset($context["customTravisBuildSteps"]) ? $context["customTravisBuildSteps"] : $this->getContext($context, "customTravisBuildSteps")), "before_install", array()), "before", array());
            echo "

";
        }
        // line 67
        echo "  # do not use the Zend allocator on PHP 5.3 since it will randomly segfault after program execution
  - '[[ \"\$TRAVIS_PHP_VERSION\" == 5.3* ]] && export USE_ZEND_ALLOC=0 || true'
";
        // line 69
        if ((!twig_test_empty((($this->getAttribute($this->getAttribute((isset($context["customTravisBuildSteps"]) ? $context["customTravisBuildSteps"] : null), "before_install", array(), "any", false, true), "after", array(), "any", true, true)) ? (_twig_default_filter($this->getAttribute($this->getAttribute((isset($context["customTravisBuildSteps"]) ? $context["customTravisBuildSteps"] : null), "before_install", array(), "any", false, true), "after", array()))) : (""))))) {
            // line 70
            echo "
";
            // line 71
            echo $this->getAttribute($this->getAttribute((isset($context["customTravisBuildSteps"]) ? $context["customTravisBuildSteps"] : $this->getContext($context, "customTravisBuildSteps")), "before_install", array()), "after", array());
            echo "
";
        }
        // line 73
        echo "
install:
";
        // line 75
        if ((!twig_test_empty((($this->getAttribute($this->getAttribute((isset($context["customTravisBuildSteps"]) ? $context["customTravisBuildSteps"] : null), "install", array(), "any", false, true), "before", array(), "any", true, true)) ? (_twig_default_filter($this->getAttribute($this->getAttribute((isset($context["customTravisBuildSteps"]) ? $context["customTravisBuildSteps"] : null), "install", array(), "any", false, true), "before", array()))) : (""))))) {
            echo $this->getAttribute($this->getAttribute((isset($context["customTravisBuildSteps"]) ? $context["customTravisBuildSteps"] : $this->getContext($context, "customTravisBuildSteps")), "install", array()), "before", array());
            echo "

";
        }
        // line 78
        if ((!twig_test_empty((isset($context["pluginName"]) ? $context["pluginName"] : $this->getContext($context, "pluginName"))))) {
            // line 79
            echo "  # move all contents of current repo (which contains the plugin) to a new directory
  - mkdir \$PLUGIN_NAME
  - cp -R !(\$PLUGIN_NAME) \$PLUGIN_NAME
  - cp -R .git/ \$PLUGIN_NAME/
  - cp .travis.yml \$PLUGIN_NAME

  # checkout piwik in the current directory
  - git clone https://github.com/piwik/piwik.git piwik
  - cd piwik
  - git fetch --all
  - | 
    if [ \"\$TEST_AGAINST_PIWIK_BRANCH\" == \"\" ]; then
        if [ \"\$TEST_AGAINST_CORE\" == \"latest_stable\" ]; then
            export TEST_AGAINST_PIWIK_BRANCH=\$(git describe --tags `git rev-list --tags --max-count=1`)
            export TEST_AGAINST_PIWIK_BRANCH=`echo \$TEST_AGAINST_PIWIK_BRANCH | tr -d ' ' | tr -d '\\n'`
        else
            export TEST_AGAINST_PIWIK_BRANCH=master
        fi
    fi
  - echo \"Testing against '\$TEST_AGAINST_PIWIK_BRANCH'\"
  - git checkout \"\$TEST_AGAINST_PIWIK_BRANCH\"
  - git submodule init
  - git submodule update || true

  # move plugin contents to folder in the plugins subdirectory
  - rm -rf plugins/\$PLUGIN_NAME
  - mv ../\$PLUGIN_NAME plugins

  # copy .coveralls.yml if none exists
  - if [ ! -f ../coveralls.yml ];
    then cp .coveralls.yml ../coveralls.yml;
    fi

  # make sure travis test scripts are always latest (so in older releases/branches, the latest scripts will still be used)
  - git checkout master -- ./tests/travis ./plugins/TestRunner

  # clone dependent repos
  - ./tests/travis/checkout_dependent_plugins.sh
";
        } else {
            // line 118
            echo "  # make sure travis test scripts are always latest (so in older releases/branches, the latest scripts will still be used)
  - git fetch
  - git checkout master -- ./tests/travis ./plugins/TestRunner || true
";
        }
        // line 122
        if ((!twig_test_empty((($this->getAttribute($this->getAttribute((isset($context["customTravisBuildSteps"]) ? $context["customTravisBuildSteps"] : null), "install", array(), "any", false, true), "after", array(), "any", true, true)) ? (_twig_default_filter($this->getAttribute($this->getAttribute((isset($context["customTravisBuildSteps"]) ? $context["customTravisBuildSteps"] : null), "install", array(), "any", false, true), "after", array()))) : (""))))) {
            // line 123
            echo "
";
            // line 124
            echo $this->getAttribute($this->getAttribute((isset($context["customTravisBuildSteps"]) ? $context["customTravisBuildSteps"] : $this->getContext($context, "customTravisBuildSteps")), "install", array()), "after", array());
            echo "
";
        }
        // line 126
        echo "
before_script:
";
        // line 128
        if ((!twig_test_empty((($this->getAttribute($this->getAttribute((isset($context["customTravisBuildSteps"]) ? $context["customTravisBuildSteps"] : null), "before_script", array(), "any", false, true), "before", array(), "any", true, true)) ? (_twig_default_filter($this->getAttribute($this->getAttribute((isset($context["customTravisBuildSteps"]) ? $context["customTravisBuildSteps"] : null), "before_script", array(), "any", false, true), "before", array()))) : (""))))) {
            echo $this->getAttribute($this->getAttribute((isset($context["customTravisBuildSteps"]) ? $context["customTravisBuildSteps"] : $this->getContext($context, "customTravisBuildSteps")), "before_script", array()), "before", array());
            echo "

";
        }
        // line 131
        echo "  - if ([ -z \"\$TEST_SUITE\" ] || [ -n \"\$PLUGIN_NAME\" ]);
    then composer require satooshi/php-coveralls dev-master;
    else
    phpenv config-rm xdebug.ini;
    fi

  - ./tests/travis/configure_git.sh

  # print out mysql information
  - mysql --version
  - mysql -e \"SELECT VERSION();\"

  # configure mysql
  - mysql -e \"SET GLOBAL sql_mode = 'NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES'\" # Travis default

  # Uncomment to enable sql_mode STRICT_TRANS_TABLES (new default in Mysql 5.6)
  - mysql -e \"SET GLOBAL sql_mode = 'NO_ENGINE_SUBSTITUTION'\"
  - mysql -e \"SELECT @@sql_mode;\"
  - mysql -e \"SHOW GLOBAL VARIABLES;\"
";
        // line 150
        if (twig_test_empty((isset($context["pluginName"]) ? $context["pluginName"] : $this->getContext($context, "pluginName")))) {
            // line 151
            echo "
  # Start UI tests
  - ./tests/travis/initiate_ui_tests.sh";
        }
        // line 155
        echo "
  # travis now complains about this failing 9 times out of 10, so removing it. hopefully the random failures it prevented won't come back
  # - travis_retry composer self-update

  - travis_retry composer install

  # print out more debugging info
  - uname -a
  - date
  - php -r \"var_dump(gd_info());\"
  - mysql -e 'create database piwik_tests;'

  # Make sure we use Python 2.6
  - travis_retry sudo add-apt-repository ppa:fkrull/deadsnakes -y
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install python2.6 python2.6-dev -y --force-yes

  # Log Analytics works with Python 2.6 or 2.7 but we want to test on 2.6
  - python2.6 --version
  - python --version

  - ./tests/travis/prepare.sh
  - ./tests/travis/setup_webserver.sh

  - export GENERATE_TRAVIS_YML_COMMAND=\"";
        // line 179
        echo (isset($context["consoleCommand"]) ? $context["consoleCommand"] : $this->getContext($context, "consoleCommand"));
        echo "\"
  - ./tests/travis/autoupdate_travis_yml.sh

  - cd tests/PHPUnit
";
        // line 183
        if ((!twig_test_empty((($this->getAttribute($this->getAttribute((isset($context["customTravisBuildSteps"]) ? $context["customTravisBuildSteps"] : null), "before_script", array(), "any", false, true), "after", array(), "any", true, true)) ? (_twig_default_filter($this->getAttribute($this->getAttribute((isset($context["customTravisBuildSteps"]) ? $context["customTravisBuildSteps"] : null), "before_script", array(), "any", false, true), "after", array()))) : (""))))) {
            // line 184
            echo "
";
            // line 185
            echo $this->getAttribute($this->getAttribute((isset($context["customTravisBuildSteps"]) ? $context["customTravisBuildSteps"] : $this->getContext($context, "customTravisBuildSteps")), "before_script", array()), "after", array());
            echo "
";
        }
        // line 187
        echo "
after_script:
";
        // line 189
        if ((!twig_test_empty((($this->getAttribute($this->getAttribute((isset($context["customTravisBuildSteps"]) ? $context["customTravisBuildSteps"] : null), "after_script", array(), "any", false, true), "before", array(), "any", true, true)) ? (_twig_default_filter($this->getAttribute($this->getAttribute((isset($context["customTravisBuildSteps"]) ? $context["customTravisBuildSteps"] : null), "after_script", array(), "any", false, true), "before", array()))) : (""))))) {
            echo $this->getAttribute($this->getAttribute((isset($context["customTravisBuildSteps"]) ? $context["customTravisBuildSteps"] : $this->getContext($context, "customTravisBuildSteps")), "after_script", array()), "before", array());
            echo "

";
        }
        // line 192
        echo "  # change directory back to root travis dir
  - cd \$PIWIK_ROOT_DIR

  - if ([ -z \"\$TEST_SUITE\" ] || [ -n \"\$PLUGIN_NAME\" ]);
    then php vendor/bin/coveralls -v;
    fi

  # output contents of files w/ debugging info to screen
  - cat /var/log/nginx/error.log
  - cat \$PIWIK_ROOT_DIR/tmp/php-fpm.log
  - cat \$PIWIK_ROOT_DIR/tmp/logs/piwik.log
  - cat \$PIWIK_ROOT_DIR/config/config.ini.php

  # upload test artifacts (for debugging travis failures)
  - ./tests/travis/upload_artifacts.sh
";
        // line 207
        if ((!twig_test_empty((($this->getAttribute($this->getAttribute((isset($context["customTravisBuildSteps"]) ? $context["customTravisBuildSteps"] : null), "after_script", array(), "any", false, true), "after", array(), "any", true, true)) ? (_twig_default_filter($this->getAttribute($this->getAttribute((isset($context["customTravisBuildSteps"]) ? $context["customTravisBuildSteps"] : null), "after_script", array(), "any", false, true), "after", array()))) : (""))))) {
            // line 208
            echo "
";
            // line 209
            echo $this->getAttribute($this->getAttribute((isset($context["customTravisBuildSteps"]) ? $context["customTravisBuildSteps"] : $this->getContext($context, "customTravisBuildSteps")), "after_script", array()), "after", array());
            echo "
";
        }
        // line 211
        echo "
after_success:
";
        // line 213
        if ((!twig_test_empty((($this->getAttribute($this->getAttribute((isset($context["customTravisBuildSteps"]) ? $context["customTravisBuildSteps"] : null), "after_success", array(), "any", false, true), "before", array(), "any", true, true)) ? (_twig_default_filter($this->getAttribute($this->getAttribute((isset($context["customTravisBuildSteps"]) ? $context["customTravisBuildSteps"] : null), "after_success", array(), "any", false, true), "before", array()))) : (""))))) {
            echo $this->getAttribute($this->getAttribute((isset($context["customTravisBuildSteps"]) ? $context["customTravisBuildSteps"] : $this->getContext($context, "customTravisBuildSteps")), "after_success", array()), "before", array());
            echo "

";
        }
        // line 216
        echo "  - cd \$PIWIK_ROOT_DIR
";
        // line 217
        if (twig_test_empty((isset($context["pluginName"]) ? $context["pluginName"] : $this->getContext($context, "pluginName")))) {
            echo "  - ./tests/travis/generate_docs.sh
";
        }
        // line 219
        if ((!twig_test_empty((($this->getAttribute($this->getAttribute((isset($context["customTravisBuildSteps"]) ? $context["customTravisBuildSteps"] : null), "after_success", array(), "any", false, true), "after", array(), "any", true, true)) ? (_twig_default_filter($this->getAttribute($this->getAttribute((isset($context["customTravisBuildSteps"]) ? $context["customTravisBuildSteps"] : null), "after_success", array(), "any", false, true), "after", array()))) : (""))))) {
            // line 220
            echo "
";
            // line 221
            echo $this->getAttribute($this->getAttribute((isset($context["customTravisBuildSteps"]) ? $context["customTravisBuildSteps"] : $this->getContext($context, "customTravisBuildSteps")), "after_success", array()), "after", array());
            echo "
";
        }
        // line 223
        if ((!twig_test_empty(((array_key_exists("extraSections", $context)) ? (_twig_default_filter((isset($context["extraSections"]) ? $context["extraSections"] : $this->getContext($context, "extraSections")))) : (""))))) {
            // line 224
            echo "
";
            // line 225
            echo trim((isset($context["extraSections"]) ? $context["extraSections"] : $this->getContext($context, "extraSections")));
        }
    }

    public function getTemplateName()
    {
        return "@TestRunner/travis.yml.twig";
    }

    public function isTraitable()
    {
        return false;
    }

    public function getDebugInfo()
    {
        return array (  424 => 225,  421 => 224,  419 => 223,  414 => 221,  411 => 220,  409 => 219,  404 => 217,  401 => 216,  394 => 213,  390 => 211,  385 => 209,  382 => 208,  380 => 207,  363 => 192,  356 => 189,  352 => 187,  347 => 185,  344 => 184,  342 => 183,  335 => 179,  309 => 155,  304 => 151,  302 => 150,  281 => 131,  274 => 128,  270 => 126,  265 => 124,  262 => 123,  260 => 122,  254 => 118,  213 => 79,  211 => 78,  204 => 75,  200 => 73,  195 => 71,  192 => 70,  190 => 69,  186 => 67,  179 => 64,  173 => 60,  168 => 58,  165 => 57,  155 => 53,  150 => 52,  143 => 50,  139 => 49,  135 => 47,  133 => 46,  131 => 45,  128 => 44,  123 => 42,  120 => 41,  105 => 38,  102 => 37,  88 => 35,  84 => 33,  80 => 31,  78 => 30,  74 => 29,  70 => 27,  68 => 26,  64 => 24,  51 => 21,  48 => 20,  41 => 15,  39 => 14,  34 => 11,  24 => 3,  22 => 2,  19 => 1,);
    }
}
